### ISSUE TITLE
Hardcoded paths in NanonisHelper.vi

### ISSUE THREAD

**Issue by benlowe1** [New-Horizons-SPM/G80-nanonis-labview#1]
Cloned G80-nanonis-labview to G81 Windows 7 computer (which has LabView 2016 installed) and tried to run NanonisHelper.vi as a starting point. It seems to be working okay, but as expected flags an error relating to different hardcoded text file paths that exist within the VI: 
![image (4)](https://user-images.githubusercontent.com/62574924/131061642-9bceea4b-5311-4296-915a-cf14a8dee63c.png)

**Comment by jhellerstedt** [comment]
turns out we really need to get this fixed because nothing runs until this is running so I can't just get this going on an independent test machine.

I'm going to:
1. Figure out how to make these relative paths to the temp folder in the git repo
2. put in a .gitignore for the temp folder/ all of these files.

**Comment by jhellerstedt** [comment]
fixed by https://github.com/New-Horizons-SPM/G80-nanonis-labview/pull/10
